In [48]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.arange(5)
c=np.arange(1,8,2)
print(a)
print(b)
print(c)

[1 2 3 4 5]
[0 1 2 3 4]
[1 3 5 7]


### 四则运算

In [49]:
d=a-b  #shape 相同  对应位置计算
print(c)

[1 3 5 7]


In [50]:
print(b*2) #每个位置乘2

[0 2 4 6 8]


In [51]:
print(a*b)

[ 0  2  6 12 20]


### 幂运算

In [52]:
print(b**2) #幂运算
print(b**3) #幂运算

[ 0  1  4  9 16]
[ 0  1  8 27 64]


### 逻辑运算

In [53]:
print(a%2==0) #逻辑运算

[False  True False  True False]


### 多维度计算

In [54]:
A=np.array([[1,2],
            [0,1]])
B=np.array([[2,0],[3,4]])
            
print(A)
print(B)

[[1 2]
 [0 1]]
[[2 0]
 [3 4]]


In [55]:
print(A*B)#相同位置相乘

[[2 0]
 [0 4]]


### 矩阵Dot 乘法

In [56]:
print(A.dot(B)) #矩阵乘法
print(np.dot(A,B)) #矩阵乘法

[[8 8]
 [3 4]]
[[8 8]
 [3 4]]


### 幂次方运算

In [64]:
print(np.exp(A)) #E的次方
print(A**2) # A的2次方

[[ 2.71828183  7.3890561 ]
 [ 1.          2.71828183]]
[[1 4]
 [0 1]]


### 开根号运算

In [65]:
print(np.sqrt(B))

[[ 1.41421356  0.        ]
 [ 1.73205081  2.        ]]


In [78]:
aa1=10*np.random.random((3,4))
print(aa1)

print(np.floor(10*np.random.random((3,4))))#向下取整

[[ 6.68394125  3.60974532  3.94822795  9.04235696]
 [ 5.24433944  1.10990834  4.6501794   8.96817074]
 [ 0.48675701  8.43067014  8.67340486  1.30092549]]
[[ 8.  8.  4.  1.]
 [ 7.  5.  0.  6.]
 [ 6.  7.  3.  9.]]


### ravel 拉平矩阵 和reshape 相反

In [91]:
print(aa1.ravel())# 拉平
#aa1.shape=(6,2) #重新定义shape   
aa1.shape=(6,-1) #重新定义shape   -1表示 自动计算第二个维度值
print(aa1)

[ 6.68394125  3.60974532  3.94822795  9.04235696  5.24433944  1.10990834
  4.6501794   8.96817074  0.48675701  8.43067014  8.67340486  1.30092549]
[[ 6.68394125  3.60974532]
 [ 3.94822795  9.04235696]
 [ 5.24433944  1.10990834]
 [ 4.6501794   8.96817074]
 [ 0.48675701  8.43067014]
 [ 8.67340486  1.30092549]]


In [90]:
print(aa1.T) #矩阵转置

[[ 6.68394125  3.94822795  5.24433944  4.6501794   0.48675701  8.67340486]
 [ 3.60974532  9.04235696  1.10990834  8.96817074  8.43067014  1.30092549]]
