In [1]:
import numpy


In [3]:
numbs=numpy.array([3,3,5,6,7,6,3])

In [10]:
numbs==10


array([False, False, False, False, False, False, False], dtype=bool)

In [7]:
a.dtype

dtype('bool')

In [16]:
nb2=numpy.array([
    [1,2,3,4,],
    [11,22,33,44],
    [33,44,45,66]
])

In [17]:
print(nb2)

[[ 1  2  3  4]
 [11 22 33 44]
 [33 44 45 66]]


In [38]:
#返回等于33的矩阵

eaqual_to_33=(nb2==33)
print(eaqual_to_33)


[[False False False False]
 [False False  True False]
 [ True False False False]]


In [35]:
nb3=numpy.array([1,2,3,4,5,3])
print(nb3)

[1 2 3 4 5 3]


In [36]:
eq=nb3==3
print(eq)

[False False  True False False  True]


In [37]:
print(nb3[eq])

[3 3]


In [46]:
#取出第四列存在66的行数据
print(nb2[:,3])
eq2=(nb2[:,3]==66)
print(eq2)
print(nb2[eq2,:])


[ 4 44 66]
[False False  True]
[[33 44 45 66]]


In [47]:
nb4=numpy.array([1,2,3,4,5,])
print(nb4)

[1 2 3 4 5]


In [52]:
eq3=(nb4==2)&(nb4==5)
print(eq3)
eq3=(nb4==2)|(nb4==5)
print(eq3)

[False False False False False]
[False  True False False  True]
