In [13]:
import numpy as np

## 合并

In [19]:
#  创建2*2 随机矩阵
a=np.floor(10*np.random.random((2,2)))
b=np.floor(10*np.random.random((2,2)))
print(a)
print("________________")
print(b)

[[ 3.  1.]
 [ 4.  9.]]
________________
[[ 4.  6.]
 [ 3.  0.]]


### 1.横向拼接  hstack

In [21]:
print(np.hstack((a,b)))

[[ 3.  1.  4.  6.]
 [ 4.  9.  3.  0.]]


### 2.纵向拼接 vstack

In [22]:
print(np.vstack((a,b)))

[[ 3.  1.]
 [ 4.  9.]
 [ 4.  6.]
 [ 3.  0.]]


## 拆分

In [23]:
A=np.floor(10* np.random.random((2,12)))
print(A)

[[ 0.  2.  6.  3.  0.  9.  0.  5.  7.  3.  0.  3.]
 [ 6.  6.  1.  7.  1.  0.  2.  1.  1.  7.  4.  9.]]


### 1.横向拆分

In [34]:
print(np.hsplit(A,3))
#每三行拆分必须整除

[array([[ 0.,  2.,  6.,  3.],
       [ 6.,  6.,  1.,  7.]]), array([[ 0.,  9.,  0.,  5.],
       [ 1.,  0.,  2.,  1.]]), array([[ 7.,  3.,  0.,  3.],
       [ 1.,  7.,  4.,  9.]])]


In [43]:
print(np.hsplit(A,(3,4)))   #元组 刀位
#split a after the third and fourth column
#在第三行和第四切分

[array([[ 0.,  2.,  6.],
       [ 6.,  6.,  1.]]), array([[ 3.],
       [ 7.]]), array([[ 0.,  9.,  0.,  5.,  7.,  3.,  0.,  3.],
       [ 1.,  0.,  2.,  1.,  1.,  7.,  4.,  9.]])]


### 2.纵向拆分

In [47]:
print(np.vsplit(A,2))

[array([[ 0.,  2.,  6.,  3.,  0.,  9.,  0.,  5.,  7.,  3.,  0.,  3.]]), array([[ 6.,  6.,  1.,  7.,  1.,  0.,  2.,  1.,  1.,  7.,  4.,  9.]])]
