In [2]:
import numpy as np

In [13]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### 引用copy

In [19]:
b=a
print(b)
print(a is b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
True


#### 改变其中一个结构 另外一个也变

In [18]:
b.shape=3,4
print(b)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### 两个内存地址一样

In [24]:
print(id(a))
print(id(b))

3105071703984
3105071703984


### 赋值拷贝

#### 变换结构不影响原有结构

In [34]:
c=a.view() 
c.shape=2,6
print(a)
print("___________________")
print(c)


[[1223    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
___________________
[[1223    1    2    3    4    5]
 [   6    7    8    9   10   11]]


#### 改变值则 影响原有值   ID不同  共用一套值

In [38]:

c[0,0]=1223
print(a)
print(c)
print(id(a))
print(id(c))


[[1223    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
[[1223    1    2    3    4    5]
 [   6    7    8    9   10   11]]
3105071703984
3105071768320


### 全复制
##### this  copy method makes  a complete copy of the array and its data

In [37]:
d=a.copy()
d[0,0]=9999
print(a)
print(d)

[[1223    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
[[9999    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
