In [2]:
import numpy as np

## 构造矩阵 并求sin 值

In [3]:
data=np.sin(np.arange(20).reshape(5,-1))
print(data)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]


##  1.求第一维度最大数

In [6]:
ind= data.max(axis=0)
print(ind)

[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


## 2.求第一维度最大数所在索引

In [12]:
ind2= data.argmax(axis=0)
print(ind2)

[2 0 3 1]


## 3.通过索引求最大值

In [18]:
print(data[ind2,range(data.shape[1])])

[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


## 矩阵拓展 倍展

In [25]:
a=np.arange(0,40,10)
print(a)

[ 0 10 20 30]


In [ ]:
### 横变2倍 纵3倍

In [26]:
b=np.tile(a,(2,3))
print(b)
print(b.shape)

[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]
(2, 12)


## 矩阵排序

In [41]:
A=np.array([[4,3,5],[1,2,1]])
print(A)

[[4 3 5]
 [1 2 1]]


### 对列进行排序

In [44]:
B=np.sort(A,axis=1)
print(B)

[[3 4 5]
 [1 1 2]]


## 排序索引

In [43]:
J=np.argsort(A)
print(J)

[[1 0 2]
 [0 2 1]]
